---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - reverse-proxy.app-scape.de
  resources:
  - reverseproxyentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reverse-proxy.app-scape.de
  resources:
  - reverseproxyentries/finalizers
  verbs:
  - update
- apiGroups:
  - reverse-proxy.app-scape.de
  resources:
  - reverseproxyentries/status
  verbs:
  - get
  - patch
  - update
